# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='name')),
                ('balance', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance')),
            ],
        ),
        migrations.CreateModel(
            name='Executer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='name')),
                ('balance', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
