# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='executer',
            name='balance',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='executer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
