version: '2'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 27101967mirzigul
      MYSQL_DATABASE: data
    volumes:
      - /var/lib/mysql
  web:
    restart: always
    build: .
    command: bash -c "python3 ./manage.py migrate && python3 ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000"
    depends_on:
      - db