# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='price')),
                ('description', models.CharField(max_length=400, verbose_name='description')),
                ('owner', models.TextField()),
                ('created_by', models.TextField()),
            ],
        ),
    ]
