# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'title')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'price')),
                ('description', models.CharField(max_length=400, verbose_name=b'description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name=b'created_by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Executer', verbose_name=b'owner')),
            ],
        ),
    ]
